# Pandas Series
- One Dimensional

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
s1 = pd.Series([1,2,3,4,5])
print(type(s1))
s1

<class 'pandas.core.series.Series'>

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
# How to add column name
display(s1)

s1 = pd.Series([1,2,3,4,5], name = 'Column1')
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

0    1
1    2
2    3
3    4
4    5
Name: Column1, dtype: int64

In [ ]:
df = pd.DataFrame(s1, columns=['New_column'])
df

Empty DataFrame
Columns: [New_column]
Index: []

In [ ]:
s1

0    1
1    2
2    3
3    4
4    5
Name: Column1, dtype: int64

In [ ]:
s1['5'] = 11
s1

0           1
1           2
2           3
3           4
4           5
Column2    11
5          11
dtype: object

In [ ]:
s2 = pd.Series([1, 2, 3, 4])
s2

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
s2['Col1'] = pd.Series([11,12,13,14])
s2

0                                                  1
1                                                  2
2                                                  3
3                                                  4
Col1    0    11
1    12
2    13
3    14
dtype: int64
dtype: object